// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flecedwdedatgkijskcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZWNlZHdkZWRhdGdraWpza2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzA3MjIsImV4cCI6MjA2NzA0NjcyMn0.zKZLs0T-7H8JmRhyAJfzklaDJ1cCOIOle7QI7MVYwu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});